server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1111

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 800MB
      max-request-size: 800MB

  jpa:
    hibernate:
      ddl-auto: none
